version: '3'
services:
  php:
    image: yiisoftware/yii2-php:8.0-apache
    container_name: test-task-php
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8080:80'
    links:
      - db
  db:
    image: mysql:latest
    restart: always
    container_name: test-task-db
    ports:
      - 33061:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: test-task
      MYSQL_ROOT_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
  
volumes:
  mysql_data:
